[versions]
agp = "7.1.2"
kotlin = "1.6.10"
coroutines = "1.6.0"

androidxhilt = "1.0.0"
androidxlifecycle = "2.4.1"
compose = "1.1.1"
hilt = "2.41"
room = "2.4.2"
work = "2.7.1"

[plugins]
detekt = { id = "io.gitlab.arturbosch.detekt", version = "1.19.0" }

[libraries]
android-gradlePluginClasspath = { module = "com.android.tools.build:gradle", version.ref = "agp" }

androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxhilt" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidxhilt" }

androidx-activity-compose = { module = "androidx.activity:activity-compose", version = "1.4.0" }
androidx-lifecycle-viewmodel-compose = { module = "androidx.lifecycle:lifecycle-viewmodel-compose", version.ref = "androidxlifecycle" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }

androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }

compose-material-material = { module = "androidx.compose.material:material", version.ref = "compose" } # Material Design
#compose-material-material3 = { module = "androidx.compose.material3:material3", version = "1.0.0-alpha04" }
compose-ui = { module = "androidx.compose.ui:ui", version.ref = "compose" }
compose-ui-test = { module = "androidx.compose.ui:ui-test-junit4", version.ref = "compose" }
compose-ui-tooling = { module = "androidx.compose.ui:ui-tooling", version.ref = "compose" } # Tooling support (Previews, etc.)

google-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
google-hilt-gradlePluginClasspath = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
google-hilt-library = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
#google-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

#dokka = "org.jetbrains.dokka:dokka-gradle-plugin:1.4.30"

junit-bom = "org.junit:junit-bom:5.8.2"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }

kotlin-binaryCompatibility = "org.jetbrains.kotlinx:binary-compatibility-validator:0.3.0"
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-gradlePluginClasspath = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

mockK = "io.mockk:mockk:1.12.3"

timber = "com.jakewharton.timber:timber:5.0.1"

truth = "com.google.truth:truth:1.1.3"

gradleVersions-gradlePluginClasspath = "com.github.ben-manes:gradle-versions-plugin:0.42.0"













