[versions]
agp = "7.0.0-alpha15"
kotlin = "1.5.0"
coroutines = "1.5.0"

androidxhilt = "1.0.0"
androidxlifecycle = "2.3.1"
hilt = "2.35.1"
room = "2.3.0"
work = "2.5.0"

[libraries]
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }
android-desugar = "com.android.tools:desugar_jdk_libs:1.1.5"

androidx-activity = "androidx.activity:activity-ktx:1.2.3"
androidx-appcompat = "androidx.appcompat:appcompat:1.3.0-rc01"
androidx-constraintlayout = "androidx.constraintlayout:constraintlayout:2.0.4"
androidx-core = "androidx.core:core-ktx:1.5.0-rc02"
androidx-fragment = "androidx.fragment:fragment-ktx:1.3.3"
androidx-recyclerview = "androidx.recyclerview:recyclerview:1.2.0"

androidx-hilt-compiler = { module = "androidx.hilt:hilt-compiler", version.ref = "androidxhilt" }
androidx-hilt-work = { module = "androidx.hilt:hilt-work", version.ref = "androidxhilt" }

androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "androidxlifecycle" }
androidx-lifecycle-viewmodel-ktx = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "androidxlifecycle" }

androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }
androidx-room-ktx = { module = "androidx.room:room-ktx", version.ref = "room" }
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-testing = { module = "androidx.room:room-testing", version.ref = "room" }

androidx-work-runtime = { module = "androidx.work:work-runtime-ktx", version.ref = "work" }

google-hilt-compiler = { module = "com.google.dagger:hilt-android-compiler", version.ref = "hilt" }
google-hilt-gradlePlugin = { module = "com.google.dagger:hilt-android-gradle-plugin", version.ref = "hilt" }
google-hilt-library = { module = "com.google.dagger:hilt-android", version.ref = "hilt" }
google-hilt-testing = { module = "com.google.dagger:hilt-android-testing", version.ref = "hilt" }

detekt-gradlePlugin = "io.gitlab.arturbosch.detekt:detekt-gradle-plugin:1.17.0-RC2"

#dokka = "org.jetbrains.dokka:dokka-gradle-plugin:1.4.30"

junit-bom = "org.junit:junit-bom:5.7.1"
junit-jupiter = { module = "org.junit.jupiter:junit-jupiter" }
junit-engine = { module = "org.junit.jupiter:junit-jupiter-engine" }

kotlin-binaryCompatibility = "org.jetbrains.kotlinx:binary-compatibility-validator:0.3.0"
kotlin-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutines" }
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }

mockK = "io.mockk:mockk:1.11.0"

timber = "com.jakewharton.timber:timber:4.7.1"

truth = "com.google.truth:truth:1.1.2"

gradleVersions-gradlePlugin = "com.github.ben-manes:gradle-versions-plugin:0.38.0"

xerial-sqlite = "org.xerial:sqlite-jdbc:3.34.0"













